apiVersion: v1  
kind: Source  
name: iot-tracking-source 
spec:  
  kind: SQLServer  
  properties:  
    host: sql-server.usecase-drasi-one.svc.cluster.local  
    port: 1433  
    user: sa  
    password: "<YourStrong!Passw0rd>"
    database: IoTData
    encrypt: false  
    trustServerCertificate: true  
    tables:  
      - dbo.IoTTemperatureData