apiVersion: v1  
kind: Service  
metadata:  
  name: sql-server  
  namespace: usecase-drasi-one  
spec:  
  type: NodePort  
  ports:  
  - port: 1433  
    targetPort: 1433  
    nodePort: 31000
  selector:  
    app: sql-server  
---  
apiVersion: apps/v1  
kind: Deployment  
metadata:  
  name: sql-server  
  namespace: usecase-drasi-one  
spec:  
  replicas: 1  
  selector:  
    matchLabels:  
      app: sql-server  
  template:  
    metadata:  
      labels:  
        app: sql-server  
    spec:  
      containers:  
      - name: sql-server  
        image: mcr.microsoft.com/mssql/server:2019-latest  
        ports:  
        - containerPort: 1433  
        env:  
        - name: ACCEPT_EULA  
          value: "Y"  
        - name: SA_PASSWORD  
          value: "<YourStrong!Passw0rd>"  